CELL_SIZE = 30
BOARD_WIDTH = 10
BOARD_HEIGHT = 20

SIDEBAR_WIDTH = 280

WINDOW_WIDTH = BOARD_WIDTH * CELL_SIZE + SIDEBAR_WIDTH
WINDOW_HEIGHT = BOARD_HEIGHT * CELL_SIZE

BASE_FALL_INTERVAL = 0.8  # seconds at level 1
MAX_LEVEL_SPEED_MULTIPLIER = 2.0  # level 10 is 2x speed (half interval)
LINES_PER_LEVEL = 10
